### ISSUE TITLE
Update gatsby-source-graphql

### ISSUE THREAD

**Issue by MarcMcIntosh** [prismicio/gatsby-source-graphql-universal#5]
Mentioned here https://github.com/prismicio/gatsby-source-prismic-graphql/issues/15

**Comment by matthewtgilbride** [comment]
Hi @MarcMcIntosh - perhaps I'm being silly.  I'm trying to open up a PR here per the linked issue that I created.  It seems on both repositories I have access to create a PR, but I don't have access to create a branch?

```
git push --set-upstream origin update-gatsby-source-graphql-#5
remote: Permission to prismicio/gatsby-source-graphql-universal.git denied to matthewtgilbride
```

Am I missing something?

**Comment by matthewtgilbride** [comment]
I thought maybe I was pointing at the wrong remote (the upstream fork), but that doesn't seem to be the case...

```
git remote -v
origin  https://github.com/prismicio/gatsby-source-graphql-universal.git (fetch)
origin  https://github.com/prismicio/gatsby-source-graphql-universal.git (push)
```

**Comment by MarcMcIntosh** [comment]
Hi @matthewtgilbride 
Create a fork first :)

**Comment by matthewtgilbride** [comment]
> Hi @matthewtgilbride
> Create a fork first :)

Thanks, sorry.  Here you go: https://github.com/prismicio/gatsby-source-graphql-universal/pull/6
